### ISSUE TITLE
Item disappears from mini cart when incrementing quantity

### ISSUE THREAD

**Issue by arbitrary-256** [Zindrek/IMP#1]
1. Went to "Order" screen
2. Added "French Grogu" to cart
3. Clicked "+" button on item card in mini cart sidebar
4. Item disappeared from cart; cart total reset to zero.

Replicated the behavior with another item.

**Comment by arbitrary-256** [comment]
Same behavior occurs when I attempt to increment or decrement item quantity in "Cart" screen

**Comment by Zindrek** [comment]
Issue has been resolved
