### ISSUE TITLE
Add to Cart after changing quantity in cart resets quantity

### ISSUE THREAD

**Issue by mmurrell27** [Zindrek/IMP#5]
Test Steps:
1. Add a item to the cart (Quantity=1).
2. Enter (Type) a larger quantity for the item in the cart, i.e. 15.
3. Select the "ADD TO CART" button for the same item.

Expected Result:
1. The quantity in the cart shall be incremented by one.

Actual Result:
1. The quantity in the cart was reset to 2.

**Comment by Zindrek** [comment]
Resolved
