### ISSUE TITLE
Add to Cart appears to have memory from last purchase

### ISSUE THREAD

**Issue by mmurrell27** [Zindrek/IMP#6]
Test Steps:
1. Add a item to the cart (Quantity=1).
2. Enter (Type) a larger quantity for the item in the cart.
3. Select the "CART" tab.
4. select the "PURCHASE CART" button.
5. Select the "ORDER" tab.
6. Select the "ADD TO CART" button for the same item as step 1.

Expected Result:
1. The quantity in the cart shall be 1.

Actual Result:
1. The quantity in the cart was 2.  Also, if you repeat steps 2-6, the quantity will increment.

**Comment by Zindrek** [comment]
Resolved
